language: php

matrix:
  include:
    - dist: precise
      php: 5.3
    - dist: trusty
      php: 5.4
    - dist: trusty
      php: 5.5
    - dist: xenial
      php: 5.6
    - dist: xenial
      php: 7.0
    - dist: bionic
      php: 7.1
    - dist: bionic
      php: 7.2
    - dist: bionic
      php: 7.3
    - dist: bionic
      php: 7.4
    - dist: trusty
      php: hhvm-3.18

install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit --coverage-text
